- label: "'Numero de serie'"
  parameter: DeviceID.SerialNumber
  type: "'device-link'"
  components:
    - type: "'parameter'"
- label: "'Modelo'"
  parameter: DeviceID.ProductClass
- label: "'Version de software'"
  parameter: InternetGatewayDevice.DeviceInfo.SoftwareVersion
- label: "'Wan IP'"
  parameter: InternetGatewayDevice.WANDevice.1.WANConnectionDevice.1.WANIPConnection.1.ExternalIPAddress
- label: "'SSID 2.4 GHz'"
  parameter: InternetGatewayDevice.LANDevice.1.WLANConfiguration.1.SSID
- label: "'SSID 5 GHz'"
  parameter: InternetGatewayDevice.LANDevice.1.WLANConfiguration.5.SSID
- element: "'span.inform'"
  label: "'Ultimo informe'"
  parameter: DATE_STRING(Events.Inform)
  type: "'container'"
  components:
    - type: "'parameter'"
    - chart: "'online'"
      type: "'overview-dot'"
- label: "'Etiquetas'"
  parameter: Tags
  type: "'tags'"
  unsortable: true
  writable: false
